export { default as FixedPlugin } from "./FixedPlugin";
export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";
export { default as PrivateRouteWithLayout } from "./PrivateRouteWithLayout";
export { default as RouteWithLayout } from "./RouteWithLayout";
export { default as Sidebar } from "./Sidebar";
export { default as Pagination } from "./Pagination";
export { default as ModalView } from "./ModalView";
export { default as Switch } from "./Switch";
